"""empty message

Revision ID: de8b0a435192
Revises: 7adb78488e26
Create Date: 2023-04-08 01:05:29.232446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8b0a435192'
down_revision = '7adb78488e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.String(length=150), nullable=False))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('picture_url')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
